### ISSUE TITLE
formatting broken in neovim nightly as of 454ae67

### ISSUE THREAD

**Issue by higherorderfunctor** [nvimtools/none-ls.nvim#209]
### FAQ

- [X] I have checked the [FAQ](https://github.com/nvimtools/none-ls.nvim#faq) and it didn't resolve my problem.

### Issues

- [X] I have checked [existing issues](https://github.com/nvimtools/none-ls.nvim/issues?q=is%3Aissue) and there are no issues with the same problem.

### Neovim Version

NVIM v0.11.0-dev Build type: Release LuaJIT 2.1.1713773202 Run "nvim -V1 -v" for more info

### Dev Version?

- [ ] I am using a stable Neovim release version, or if I am using a dev version of Neovim I have confirmed that my issue is reproducible on a stable version.

### Operating System

nixos-unstable

### Minimal Config

```Lua
-- Any config should cause with neovim that includes changes from:
-- https://github.com/neovim/neovim/commit/454ae672aad172a299dcff7c33c5e61a3b631c90.
```

### Steps to Reproduce

```lua
vim.lsp.get_clients({ bufnr = vim.api.nvim_get_current_buf(), method = "textDocument/formatting" })
```

"self" is passed to `supports_method` at https://github.com/nvimtools/none-ls.nvim/blob/6be90f8cf37d7f50a89b7229412f6184b16f1b28/lua/null-ls/client.lua#L59 from the changes here https://github.com/neovim/neovim/blob/146b8300a145efa64e579527da8606546a36162b/runtime/lua/vim/lsp.lua#L795.

### Reproducibility Check

- [ ] I confirm that my minimal config is based on the `minimal_init.lua` template and that my issue is reproducible by running `nvim --clean -u minimal_init.lua` and following the steps above.

### Expected Behavior

Formatting to happen.

### Actual Behavior

No formatting happens.

### Debug Log

Doesn't log because the filter method is flagged as disabled at below since method is now self.

https://github.com/nvimtools/none-ls.nvim/blob/6be90f8cf37d7f50a89b7229412f6184b16f1b28/lua/null-ls/client.lua#L51

### Help

Yes, but I don't know how to start. I would need guidance

### Implementation Help

This commit: https://github.com/neovim/neovim/commit/454ae672aad172a299dcff7c33c5e61a3b631c90

Causes self to be passed here: https://github.com/nvimtools/none-ls.nvim/blob/6be90f8cf37d7f50a89b7229412f6184b16f1b28/lua/null-ls/client.lua#L59

Which can be fixed by accepting self.

```diff
-      new_client.supports_method = function(method)
+      new_client.supports_method = function(_, method)
```

I was able to find and fix the issue, but I don't know the intricacies of Lua enough or how it handles OOP to support nightly and stable at the same time.

### Requirements

- [X] I have read and followed the instructions above and understand that my issue will be closed if I did not provide the required information.

**Comment by mochaaP** [comment]
should be fixed, please check :)

**Comment by mosheavni** [comment]
Formatting is still broken in `main` branch using nvim 0.11.0
none-ls is not returning `"textDocument/formatting"`

**Comment by jfly** [comment]
@mosheavni, is it possible you are running into this issue? https://github.com/nvimtools/none-ls.nvim/pull/231

**Comment by mosheavni** [comment]
> @mosheavni, is it possible you are running into this issue? https://github.com/nvimtools/none-ls.nvim/pull/231

Yeah looks like it
